from pathlib import Path

ROOT_DIR = Path("/data")
ORIGINAL_DATA_DIR = ROOT_DIR / "original_data"
PROCESSED_DATA_DIR = ROOT_DIR / "processed_data"

# THL Birth registry
THL_BIRTH_INPUT_DIR = ORIGINAL_DATA_DIR / "thl_birth"
THL_BIRTH_OUTPUT_DIR = PROCESSED_DATA_DIR / "thl_birth"
THL_BIRTH_DATA_PATH = THL_BIRTH_INPUT_DIR / "thl2021_2196_synret.csv.finreg_IDs"

# THL Vaccination
THL_VACCINATION_INPUT_DIR = ORIGINAL_DATA_DIR / "thl_vaccination"
THL_VACCINATION_OUTPUT_DIR = PROCESSED_DATA_DIR / "thl_vaccination"
VACCINATION_PROTECTION_DATA_PATH = THL_VACCINATION_INPUT_DIR / "thl2196_rokotussuoja.csv"
VACCINATION_REGISTRY_DATA_PATH = THL_VACCINATION_INPUT_DIR / "thl2196_rokotus.csv.finreg_IDs"

# THL Infectious Diseases
THL_INFECTIOUS_DISEASES_INPUT_DIR = ORIGINAL_DATA_DIR / "thl_infectious_diseases"
THL_INFECTIOUS_DISEASES_OUTPUT_DIR = PROCESSED_DATA_DIR / "thl_infectious_diseases"
THL_INFECTIOUS_DISEASES_DATA_PATH = THL_INFECTIOUS_DISEASES_INPUT_DIR / "thl2021_2196_ttr.csv.finreg_IDs"
THL_INFECTIOUS_DISEASES_AMENDMENT_DATA_PATH = THL_INFECTIOUS_DISEASES_INPUT_DIR / "thl2196_ttr.csv.finreg_IDs"

# THL Malformations
THL_MALFORMATIONS_INPUT_DIR = ORIGINAL_DATA_DIR / "thl_malformations"
THL_MALFORMATIONS_OUTPUT_DIR = PROCESSED_DATA_DIR / "thl_malformations"
THL_MALFORMATIONS_BASIC_DATA_PATH = THL_MALFORMATIONS_INPUT_DIR / "thl2020_2196_er_basic.csv.finreg_IDs"
THL_MALFORMATIONS_ANOMALIES_DATA_PATH = THL_MALFORMATIONS_INPUT_DIR / "thl2020_2196_er_anomalies.csv.finreg_IDs"

# THL Cancer
THL_CANCER_INPUT_DIR = ORIGINAL_DATA_DIR / "thl_cancer"
THL_CANCER_OUTPUT_DIR = PROCESSED_DATA_DIR / "thl_cancer"
THL_CANCER_DATA_PATH = THL_CANCER_INPUT_DIR / "fcr_data.csv.finreg_IDs"

# THL Hilmo
THL_HILMO_INPUT_DIR = ORIGINAL_DATA_DIR / "thl_hilmo"
THL_HILMO_MAIN = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_2019_2021.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_9495.csv.finreg_IDs"]
THL_HILMO_DIAG = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_DIAG.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_diagnoosit_kaikki.csv.finreg_IDs"]
THL_HILMO_HAITMP = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_HAITMP.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_haitmp.csv.finreg_IDs"]
THL_HILMO_HHAITTA = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_HHAITTA.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_hhaitta.csv.finreg_IDs"]
THL_HILMO_LAAKKEET = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_LAAKITYS.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_laakkeet.csv.finreg_IDs"]
THL_HILMO_PSYKLAAKE = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_PSYKLAAKE.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_psykplaake.csv.finreg_IDs"]
THL_HILMO_PSYKP = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_PSYKP.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_psykp.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_9495_psykp.csv.finreg_IDs"]
THL_HILMO_PSYKPPAK = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_PSYKPPAK.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_psykppak.csv.finreg_IDs"]
THL_HILMO_SYP = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_SYP.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_syp.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_9495_syp.csv.finreg_IDs"]
THL_HILMO_TEHOHOITO = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_TEHOHOITO.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_tehohoito.csv.finreg_IDs"]
THL_HILMO_TOIMENPIDE = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_TOIMP.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_toimenpide.csv.finreg_IDs"]
THL_HILMO_TULOSYY = [THL_HILMO_INPUT_DIR / "THL2021_2196_HILMO_TULOSYY.csv.finreg_IDs", THL_HILMO_INPUT_DIR / "thl2019_1776_hilmo_tusyy.csv.finreg_IDs"]
THL_HILMO_OUTPUT_DIR = PROCESSED_DATA_DIR / "thl_hilmo"

# FICC Intensive Care
FICC_INTENSIVE_CARE_INPUT_DIR = ORIGINAL_DATA_DIR / "ficc_intensive_care"
FICC_INTENSIVE_CARE_OUTPUT_DIR = PROCESSED_DATA_DIR / "ficc_intensive_care"
FICC_INTENSIVE_CARE_TEHO_DATA_PATH = FICC_INTENSIVE_CARE_INPUT_DIR / "thl2020_2196_teho.csv.finreg_IDs"
FICC_INTENSIVE_CARE_TEHO_TISS_DATA_PATH = FICC_INTENSIVE_CARE_INPUT_DIR / "thl2020_2196_teho_tiss.csv.finreg_IDs"

# KELA Kanta
KELA_KANTA_INPUT_DIR = ORIGINAL_DATA_DIR / "kela_kanta"
KELA_KANTA_OUTPUT_DIR = PROCESSED_DATA_DIR / "kela_kanta"

# Pension
ETK_PENSION_INPUT_DIR = ORIGINAL_DATA_DIR / "etk_pension"
ETK_PENSION_OUTPUT_DIR = PROCESSED_DATA_DIR / "etk_pension"
ETK_PENSION_ELAKE_DATA_PATH = ETK_PENSION_INPUT_DIR / "etk_elake1990_2021.csv.finreg_IDs"
ETK_PENSION_PALKATON_DATA_PATH = ETK_PENSION_INPUT_DIR / "etk_palkaton2005_2021.csv.finreg_IDs"
ETK_PENSION_VUANSIOT_DATA_PATH = ETK_PENSION_INPUT_DIR / "etk_vuansiot2005_2021.csv.finreg_IDs"
ETK_PENSION_CPI_DATA_PATH = ETK_PENSION_INPUT_DIR / "consumer_price_index_1972_2021.csv"

# SF education, occupation & SES
SF_SOCIOECONOMIC_INPUT_DIR = ORIGINAL_DATA_DIR / "sf_socioeconomic"
SF_SOCIOECONOMIC_OUTPUT_DIR = PROCESSED_DATA_DIR / "sf_socioeconomic"
SF_EDUCATION_DATA_PATHS = [
    SF_SOCIOECONOMIC_INPUT_DIR / "tutkinto_u1442_a.csv.finreg_IDs",
    SF_SOCIOECONOMIC_INPUT_DIR / "tutkinto_u1442_al10_osa1.csv.finreg_IDs",
    SF_SOCIOECONOMIC_INPUT_DIR / "tutkinto_u1442_al10_osa2.csv.finreg_IDs",
]
SF_OCCUPATION_DATA_PATHS = [
    SF_SOCIOECONOMIC_INPUT_DIR / "ammatti_u1442_a.csv.finreg_IDs",
    SF_SOCIOECONOMIC_INPUT_DIR / "ammatti_u1442_al10.csv.finreg_IDs"
]
SF_SES_DATA_PATHS = [
    SF_SOCIOECONOMIC_INPUT_DIR / "sose_u1442_a.csv.finreg_IDs",
    SF_SOCIOECONOMIC_INPUT_DIR / "sose_u1442_al10.csv.finreg_IDs"
]